modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-solmate-dc/module
name: Solmate Device-Connector
version: v0.0.13
type: device-connector
deploymentType: single
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: CONF_MSGBROKER_HOST
          services:
            - mgw-solmate-dc
services:
  mgw-solmate-dc:
    name: mgw-solmate-dc
    image: ghcr.io/senergy-platform/mgw-solmate-dc:v0.0.11
configs:
  discoveryIps:
    dataType: string
    isList: true
    targets:
      - refVar: CONF_DISCOVERY_IPS
        services:
          - mgw-solmate-dc
    userInput:
      type: text
      name: Discovery IPs
      description: "List of IPs, e.g. 192.168.0.1, 192.168.0.2"
  liveSeconds:
    dataType: int
    value: 5
    targets:
      - refVar: CONF_SENERGY_EVENTS_LIVE_VALUES_SECONDS
        services:
          - mgw-solmate-dc
    userInput:
      type: number
      name: Live Data Poll Rate
      description: "refresh live data every x seconds"
  liveEnergyCap:
    dataType: int
    value: 1000
    targets:
      - refVar: CONF_SENERGY_LIVE_VALUES_CAP
        services:
          - mgw-solmate-dc
    userInput:
      type: number
      name: Live Data Energy Cap
      description: "ignore pv power values above this value"
  injectionSeconds:
    dataType: int
    value: 15
    targets:
      - refVar: CONF_SENERGY_EVENTS_INJECTION_SETTINGS_SECONDS
        services:
          - mgw-solmate-dc
    userInput:
      type: number
      name: Injection Data Poll Rate
      description: "refresh injection data every x seconds"
