modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-madoka-dc/module
name: Madoka Device-Connector
version: v0.0.3
type: device-connector
deploymentType: multiple
license: "Apache License 2.0"
dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: MQTT_HOST
          services:
            - mgw-madoka-dc
services:
  mgw-madoka-dc:
    name: mgw-madoka-dc
    image: ghcr.io/senergy-platform/mgw-madoka-dc:v0.0.3
configs:
  mqttinterval:
    dataType: int
    value: 15
    targets:
      - refVar: MQTT_INTERVAL
        services:
          - mgw-madoka-dc
    userInput:
      type: number
      name: Data Rate
      description: "refresh data every x seconds"
  mac:
    dataType: string
    value: "00:00:00:00:00:00"
    targets:
      - refVar: MADOKA_MAC
        services:
          - mgw-madoka-dc
    userInput:
      type: text
      name: Mac Address
      description: "Mac address of the madoka controller"
  adapter:
    dataType: string
    value: "hci0"
    targets:
      - refVar: BT_ADAPTER
        services:
          - mgw-madoka-dc
    userInput:
      type: text
      name: Bluetooth Controller
      description: "Specify a bluetooth controller, if you have multiple"
hostResources:
  dbus-sock:
    userInput:
      name: DBus
    targets:
      - mountPoint: "/var/run/dbus/system_bus_socket"
        services:
          - mgw-madoka-dc
