modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-analytics-fog-module
name: Analytics Fog
description: Analytics-Fog enables the gateway to start analytics pipelines on the device. It also controls the data sharing with the cloud.
version: v1.1.28
type: add-on
tags:
  - analytics
  - fog
deploymentType: single
services:
  fog-agent:
    name: Fog Agent
    image: ghcr.io/senergy-platform/analytics-fog-agent:v1.0.13
  fog-master:
    name: Fog Master
    image: ghcr.io/senergy-platform/analytics-fog-master:v1.0.6
  fog-connector:
    name: Fog Connector
    image: ghcr.io/senergy-platform/analytics-fog-connector:v1.0.9

auxServices:
  operator:
    name: Analytics-Operator

auxImageSources:
  - "ghcr.io/senergy-platform/*"
  - "github.com/SENERGY-Platform/*"

inputGroups:
  cloud-settings:
    name: Cloud settings
  cloud-auth:
    name: Authentication
    group: cloud-settings
  cloud-mqtt:
    name: MQTT
    group: cloud-settings
  cloud-api:
    name: APIs
    group: cloud-settings
  local-settings:
    name: Local settings
  agent-settings:
    name: Agent
    group: local-settings
  master-settings:
    name: Master
    group: local-settings
  
volumes:
  master-data: 
    - mountPoint: /data
      services:
        - fog-master
  agent-data: 
    - mountPoint: /data
      services:
        - fog-agent

dependencies:
  github.com/SENERGY-Platform/mgw-mqtt-broker:
    version: <v2.0.0
    requiredServices:
      broker:
        - refVar: FOG_BROKER_HOST
          services:
            - fog-agent
            - fog-master
            - fog-connector

configs:
  operatorTimeout:
    dataType: int
    value: 60
    targets:
      - refVar: CONTROL_OPERATOR_TIMEOUT
        services:
          - fog-agent
    userInput:
      type: number
      name: Timeout until operator needs to be started/stopped
      group: agent-settings

  retriesOperatorStart:
    dataType: int
    value: 2
    targets:
      - refVar: RETRIES_START_OPERATOR
        services:
          - fog-master
    userInput:
      type: number
      name: Number of retries to start operator
      group: master-settings

  debug:
    dataType: string
    value: "false"
    options:
      - "true"
      - "false"
    targets:
      - refVar: DEBUG
        services:
          - fog-connector
          - fog-master
          - fog-agent
    userInput:
      type: text
      name: Debug mode
      group: local-settings

  retryTimeoutOperatorStart:
    dataType: int
    value: 60
    targets:
      - refVar: TIMEOUT_START_OPERATOR
        services:
          - fog-master
    userInput:
      type: number
      name: Timeout between retries to start operator
      group: master-settings

  platformBrokerPort:
    dataType: int
    value: 2883
    targets:
      - refVar: PLATFORM_BROKER_PORT
        services:
          - fog-connector
    userInput:
      type: number
      name: Port of the platform mqtt broker
      group: cloud-mqtt

  platformBrokerHost:
    dataType: string
    value: "connector.senergy.infai.org"
    targets:
      - refVar: PLATFORM_BROKER_HOST
        services:
          - fog-connector
    userInput:
      type: text
      name: Hostname of the platform mqtt broker
      group: cloud-mqtt

  keycloakUrl:
    dataType: string
    value: "https://auth.senergy.infai.org/auth"
    targets:
      - refVar: KEYCLOAK_URL
        services:
          - fog-connector
    userInput:
      type: text
      name: URL to keycloak
      group: cloud-api

  fogBrokerPort:
    dataType: int
    value: 1883
    targets:
      - refVar: FOG_BROKER_PORT
        services:
          - fog-master
          - fog-agent
    userInput:
      type: number
      name: Port of the local mqtt broker
      group: local-settings

  clientID:
    dataType: string
    value: analytics-fog-connector
    targets:
      - refVar: CLIENT_ID
        services:
          - fog-connector
    userInput:
      type: text
      name: Client ID for auth
      group: cloud-auth

  moduleManagerUrl:
    dataType: string
    value: http://core-api/module-manager
    targets:
      - refVar: MODULE_MANAGER_URL
        services:
          - fog-agent

  operatorManager:
    dataType: string
    value: mgw
    targets:
      - refVar: CONTAINER_MANAGER
        services:
          - fog-agent

secrets:
  auth:
    type: basic-auth
    targets:
      - refVar: AUTH_USERNAME
        item: username
        services:
          - fog-connector 
      - refVar: AUTH_PASSWORD
        item: password
        services:
          - fog-connector 
    userInput:
      name: Auth Credentials
      group: cloud-auth