name: Validate and tag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Validate legacy modules
        run: docker run --rm --mount type=bind,src=./legacy,dst=/mnt/data,ro ghcr.io/senergy-platform/mgw-module-validator:latest -m -blk .github,.git
      - name: Validate stable modules
        run: docker run --rm --mount type=bind,src=./stable,dst=/mnt/data,ro ghcr.io/senergy-platform/mgw-module-validator:latest -m -d -blk .github,.git
      - name: Validate testing modules
        run: docker run --rm --mount type=bind,src=./testing,dst=/mnt/data,ro ghcr.io/senergy-platform/mgw-module-validator:latest -m -blk .github,.git
      - name: Create tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a ${{ github.ref_name }}-validated -m "validated commit ${{ github.sha }}"
          git push origin tag ${{ github.ref_name }}-validated --force